name: Update Zenodo Metadata

on:
  push:
    branches: [main]
    paths: ['README.md']
  workflow_dispatch:

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract README content
        id: extract
        run: |
          DESCRIPTION=$(grep -A 3 -m 1 "^#" README.md | tail -n +2 | tr -d '\n' | sed 's/^[[:space:]]*//')
          ABSTRACT=$(sed -n '/^#/,/^##/p' README.md | tail -n +2 | head -n -1 | tr -d '\n' | sed 's/^[[:space:]]*//')
          
          DESCRIPTION=$(echo "$DESCRIPTION" | sed 's/"/\\"/g')
          ABSTRACT=$(echo "$ABSTRACT" | sed 's/"/\\"/g')
          
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "abstract=$ABSTRACT" >> $GITHUB_OUTPUT
      
      - name: Update Zenodo JSON
        run: |
          jq --arg desc "${{ steps.extract.outputs.description }}" \
             --arg abs "${{ steps.extract.outputs.abstract }}" \
             '.description = $desc | .notes = $abs' .zenodo.json > .zenodo.json.new
          mv .zenodo.json.new .zenodo.json
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.zenodo.json'
          message: 'chore: update zenodo metadata from README'
          default_author: github_actions

