---
- name: Build and Install Qompass Privacy Guard (qpg) from Source
  hosts: all
  become: yes # For sudo privileges
  vars:
    qpg_user: "{{ ansible_user | default('USER') }}"
    qpg_gh_dir: "{{ lookup('env', 'HOME') | default('/home/' + qpg_user) }}/.GH"
    qpg_source_dir: "{{ qpg_gh_dir }}/qpg"
    qpg_install_dir: "/opt/qpg"
    build_dependencies:
      - make
      - gcc
      - zig
      - autoconf
      - automake
      - libtool
      - pkg-config
      - texinfo
      - gettext
      - bzip2-devel
      - zlib-devel
      - readline-devel
      - sqlite-devel
      - libusb-devel
      - gnutls-devel

  tasks:
    - name: Install build dependencies
      package:
        name: "{{ build_dependencies }}"
        state: present

    - name: Create installation directory
      file:
        path: "{{ qpg_install_dir }}"
        state: directory
        mode: "0755"

    - name: Check if source directory exists
      stat:
        path: "{{ qpg_source_dir }}"
      register: source_dir_stat

    - name: Clone GnuPG repository (if needed)
      git:
        repo: "https://github.com/qompassai/nautilus/qpg.git"
        dest: "{{ qpg_source_dir }}"
        version: "main"
      when: not source_dir_stat.stat.exists

    - name: Run autogen.sh (if needed)
      command:
        cmd: ./autogen.sh
        chdir: "{{ qpg_source_dir }}"
      args:
        creates: "{{ qpg_source_dir }}/configure"
      changed_when: true

    - name: Configure QPG
      command:
        cmd: >
          CC="zig cc" ./configure --prefix="{{ qpg_install_dir }}/" \
          --enable-keyboxd \
          CFLAGS="-O3 -march=native -mtune=native -flto" \
          LDFLAGS="-flto" \
          --enable-large-secmem \
          --enable-build-timestamp \
          --disable-maintainer-mode \
          --with-zlib={{ qpg_install_dir }} \
          --enable-key-cache=8192 \
          --with-bzip2={{ qpg_install_dir }} \
          --enable-g13=={{qpg_install_dir}} \
          --with-libgpg-error-prefix={{ qpg_install_dir }} \
          --with-libgcrypt-prefix={{ qpg_install_dir }} \
          --with-libassuan-prefix={{ qpg_install_dir }} \
          --with-libksba-prefix={{ qpg_install_dir }} \
          --with-npth-prefix={{ qpg_install_dir }} \
      args:
        chdir: "{{ qpg_source_dir }}"
      register: configure_result

    - name: Build QPG
      command:
        cmd: make
        chdir: "{{ qpg_source_dir }}"
      changed_when: true

    - name: Install QPG
      command:
        cmd: make install
        chdir: "{{ qpg_source_dir }}"
      changed_when: true

    - name: Set up environment variables
      blockinfile:
        path: /etc/profile.d/qpg.sh
        create: yes
        block: |
          export PATH={{ qpg_install_dir }}/bin:$PATH
          export LD_LIBRARY_PATH={{ qpg_install_dir }}/lib:$LD_LIBRARY_PATH
          export PKG_CONFIG_PATH={{ qpg_install_dir }}/lib/pkgconfig:$PKG_CONFIG_PATH
        mode: "0644"

    - name: Verify installation
      command:
        cmd: "{{ qpg_install_dir }}/bin/gpg --version"
      register: gpg_version
      changed_when: false

    - name: Display QPG version
      debug:
        var: gpg_version.stdout_lines
