# ~/.ansible/inventory/constructed.yml
plugin: ansible.builtin.constructed
strict: false
keyed_groups:
  - prefix: os
    key: ansible_distribution
  - prefix: arch
    key: ansible_architecture
groups:
  webservers: "'web' in (group_names)"
  databases: "'db' in (group_names)"
