---
- name: Monitor 🔥 Documentation for Changes
  hosts: localhost
  gather_facts: true
  vars:
    hash_file: "mojo_docs_hashes.json"
    urls:
      - "https://docs.modular.com/mojo/manual/"
      - "https://docs.modular.com/mojo/manual/get-started/why-mojo"
      - "https://docs.modular.com/mojo/manual/get-started/"
      - "https://docs.modular.com/mojo/manual/basics/"
      - "https://docs.modular.com/mojo/manual/basics/functions"
      - "https://docs.modular.com/mojo/manual/basics/variables"
      - "https://docs.modular.com/mojo/manual/basics/types"
      - "https://docs.modular.com/mojo/manual/basics/operators"
      - "https://docs.modular.com/mojo/manual/basics/control-flow"
      - "https://docs.modular.com/mojo/manual/basics/errors"
      - "https://docs.modular.com/mojo/manual/basics/structs"
      - "https://docs.modular.com/mojo/manual/basics/modules"
      - "https://docs.modular.com/mojo/manual/ownership/semantics"
      - "https://docs.modular.com/mojo/manual/ownership/ownership"
      - "https://docs.modular.com/mojo/manual/ownership/lifetimes"
      - "https://docs.modular.com/mojo/manual/lifecycle/"
      - "https://docs.modular.com/mojo/manual/lifecycle/life"
      - "https://docs.modular.com/mojo/manual/lifecycle/death"
      - "https://docs.modular.com/mojo/manual/parameters/traits"
      - "https://docs.modular.com/mojo/manual/parameters/"
      - "https://docs.modular.com/mojo/manual/pointers/"
      - "https://docs.modular.com/mojo/manual/pointers/unsafe"
      - "https://docs.modular.com/mojo/manual/gpu/"
      - "https://docs.modular.com/mojo/manual/gpu/basics"
      - "https://docs.modular.com/mojo/manual/layouts/"
      - "https://docs.modular.com/mojo/manual/python/integration"
      - "https://docs.modular.com/mojo/manual/python/types"
      - "https://docs.modular.com/mojo/manual/tools/debugging"
      - "https://docs.modular.com/mojo/manual/tools/gpu-debugging"
      - "https://docs.modular.com/mojo/manual/tools/testing"

  tasks:
    - name: Display timestamp
      debug:
        msg: "Checking Mojo documentation at {{ ansible_date_time.iso8601 }}"

    - name: Load previous hashes
      block:
        - name: Check if hash file exists
          stat:
            path: "{{ hash_file }}"
          register: hash_file_stat

        - name: Read hash file if it exists
          slurp:
            src: "{{ hash_file }}"
          register: hash_file_content
          when: hash_file_stat.stat.exists

        - name: Parse hash file when it exists
          set_fact:
          previous_hashes: >-{{ hash_file_content.content | b64decode | from_json }}
            when: hash_file_stat.stat.exists

        - name: Set empty dictionary when file doesn't exist
          set_fact:
            previous_hashes: {}
            when: not hash_file_stat.stat.exists

        - name: Initialize variables
          set_fact:
            current_hashes: {}
            changed_urls: []

        - name: Fetch and process each URL
          include_tasks: process_url.yml
          loop: "{{ urls }}"
          loop_control:
            loop_var: current_url

        - name: Save current hashes
          copy:
          content: "{{ current_hashes | to_json }}"
          dest: "{{ hash_file }}"

        - name: Display changes
          debug:
            msg: "Changes detected in the following pages:"
          when: changed_urls | length > 0

        - name: List changed URLs
          debug:
            msg: "- {{ item }}"
          loop: "{{ changed_urls }}"
          when: changed_urls | length > 0

        - name: Display no changes message
          debug:
            msg: "No changes detected"
          when: changed_urls | length == 0

        - name: build markdown docs
      template:
        src: templates/ansible-docs.j2
        dest: /home/phaedrus/.GH/Qompass/Mojo/modular/docs/mojodoc.md
