# ~/.ansible/vars/redis_secrets.yml
# ---------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved
---
redis_ca_cert_content: "{{ lookup('community.sops.sops', '~/.config/valkey/certs/ca.crt.enc') }}"
redis_cert_content: "{{ lookup('community.sops.sops', '~/.config/valkey/certs/valkey-ec521.crt.enc') }}"
redis_key_content: "{{ lookup('community.sops.sops', '~/.config/valkey/certs/valkey-ec521.key.enc') }}"

