# /qompassai/ansible/vars/valkey_secrets.yml
# ----------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

---
valkey_password: "{{ lookup('community.general.passwordstore', 'valkey/pass') }}"

valkey_ca_cert_path: "{{ lookup('community.general.passwordstore', 'valkey/capath') }}"
valkey_tls_cert_path: "{{ lookup('community.general.passwordstore', 'valkey/tlscpath') }}"
valkey_tls_key_path: "{{ lookup('community.general.passwordstore', 'valkey/tlskpath') }}"

valkey_bind: "{{ lookup('community.general.passwordstore', 'valkey/bind') }}"
valkey_port: "{{ lookup('community.general.passwordstore', 'valkey/port') }}"
valkey_tls_port: "{{ lookup('community.general.passwordstore', 'valkey/tls_port') }}"
