---
- name: Update all Qompass repositories with metadata
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    qompass_dir: "/home/phaedrus/.GH/Qompass"
   
  tasks:
    - name: Find all Git repositories under Qompass
      find:
        paths: "{{ qompass_dir }}"
        patterns: '.git'
        file_type: directory
        recurse: yes
      register: found_repos

    - name: Set list of repository root paths
      set_fact:
        repo_paths: "{{ found_repos.files | map(attribute='path') | map('dirname') | list | unique }}"

    - name: Pull latest changes in each repository
      shell: |
        git -C "{{ item }}" pull --ff-only
      loop: "{{ repo_paths }}"
      ignore_errors: true
      register: git_pull_results

    - name: Update metadata using mu script in each repository
      shell: |
        set -euo pipefail
        ~/.local/bin/mu
      args:
        chdir: "{{ item }}"
      loop: "{{ repo_paths }}"
      ignore_errors: true
      register: mu_update_results

    - name: Add and commit updated metadata if needed
      shell: |
        set -euo pipefail
        git add .zenodo.json || true
        if ! git diff --cached --quiet; then
          git commit -m "Update metadata with mu script"
          git push
        fi
      args:
        chdir: "{{ item }}"
      loop: "{{ repo_paths }}"
      ignore_errors: true
      register: commit_push_results

    - name: Report git pull results
      debug:
        var: git_pull_results.results

    - name: Report metadata update results
      debug:
        var: mu_update_results.results

    - name: Report commit and push results
      debug:
        var: commit_push_results.results

