# /qompassai/ansible/inventory/group-vars/all.yml
# ---------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

---
ansible_ssh_private_key_file: "{{ lookup('community.sops.sops', '~/.ansible/keys/ansible_key.pem.enc') | ansible.builtin.tempfile }}"

